version: "3.8"
services:
  db-init:
    image: panda-game-init:latest
    environment:
      - DB_ADDR=ws://surreal:8000
      - DB_ADMIN=pandaAdmin
      - DB_ADMIN_PASS=strongpassword
      - DB_NS=pandaNS
      - DB_DB=pandaDB
    depends_on:
      - surreal
  game-server:
    image: panda-game-server:latest
    environment:
      - DB_ADDR=ws://surreal:8000
      - DB_ADMIN=pandaAdmin
      - DB_ADMIN_PASS=strongpassword
      - DB_NS=pandaNS
      - DB_DB=pandaDB
      - NATS_ADDR=nats://nats:4222
      - NATS_RELAY_SUBJECT=events
      - NATS_GROUPS_BUCKET=groups
      - SCALE=COLOCATED
    restart: always
    depends_on:
      - db-init
      - nats
      - surreal
    ports:
      - 3000:3000
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--js"
  surreal:
    image: surrealdb:latest
    container_name: surreal
    ports:
      - 8000:8000
    entrypoint: ["/surreal", "start", "--user","pandaAdmin", "--pass", "strongpassword"]

