version: "3.8"
services:
  pb-init:
    image: panda-game-init:latest
    environment:
      - PB_ADDR=http://pocketbase:8080
      - PB_ADMIN=admin@panda-game.com
      - PB_ADMIN_PASS=strongpassword
    depends_on:
      - pocketbase
  game-server:
    image: panda-game-server:latest
    environment:
      - PB_ADDR=http://pocketbase:8080
      - PB_ADMIN=admin@panda-game.com
      - PB_ADMIN_PASS=strongpassword
      - NATS_ADDR=nats://nats:4222
      - NATS_RELAY_SUBJECT=events
      - NATS_GROUPS_BUCKET=groups
      - SCALE=COLOCATED
    restart: always
    depends_on:
      - pb-init
      - nats
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--js"
  pocketbase:
    image: panda-game-pocketbase:latest
    container_name: pocketbase
    ports:
      - 8080:8080
    volumes:
      - type: bind
        target: /pb/pb_data
        source: ./pb_data
        bind: 
          create_host_path: true
          selinux: z

