version: "3.8"
services:
  game-server:
    image: panda-game-server:latest
    container_name: pandagame
    environment:
      - DB_ADDR=ws://surreal:8000
      - DB_HTTP_ADDR=http://surreal:8000
      - DB_ADMIN=pandaAdmin
      - DB_PASS=strongpassword
      - DB_NS=pandaNS
      - DB_DB=pandaDB
      - NATS_ADDR=nats://nats:4222
      - NATS_RELAY_SUBJECT=events
      - NATS_GROUPS_BUCKET=groups
      - SCALE=COLOCATED
    restart: always
    depends_on:
      - nats
      - surreal
    ports:
      - 3000:3000
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--js"
  surreal:
    image: surrealdb/surrealdb:latest-dev
    container_name: surreal
    ports:
      - 8000:8000
    command: [ "start", "--user", "pandaAdmin", "--pass", "strongpassword"]
    environment:
      - SURREAL_IMPORT_FILE=/panda/players.suql
      - SURREAL_PATH=rocksdb:/panda/db_data
      - SURREAL_LOG=debug
    volumes:
      - type: bind
        target: /panda/players.suql
        source: ./players.suql
      - type: bind
        target: /panda/db_data
        source: ./db_data
        read_only: false
        bind:
          create_host_path: true
          selinux: Z

