version: "3.8"
services:
  game-server:
    image: panda-game-server:latest
    environment:
      - PB_ADDR=http://pocketbase:8080
      - PB_ADMIN=admin@panda-game.com
      - PB_ADMIN_PASS=strongpassword
      - NATS_ADDR=nats://nats:4222
      - NATS_RELAY_SUBJECT=events
      - NATS_GROUPS_BUCKET=groups
      - SCALE=COLOCATED
    restart: always
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--js"
  pocketbase:
    build: 
      dockerfile: ./pocketbase.Dockerfile
    container_name: pocketbase
    ports:
      - 8080:8080
