version: "3"

tasks:
  default:
    cmds:
      - task -l
  build-dir:
    internal: true
    dir: backend
    cmds: 
      - mkdir .build
    status:
      - test -d .build
  build:
    desc: compile the backend server application
    deps: [build-dir]
    dir: backend
    cmds:
      - go build -o .build/panda-game-server cmd/panda-game/main.go
    sources:
      - ./**/*.go
    generates:
      - .build/panda-game-server
  mocks:
    desc: generate mock implementations of interfaces
    dir: backend
    cmds:
      - mockery
    sources:
      - ./**/*.go
      - ./.mockery.yaml
    generates:
      - ./**/mock_*.go
  unit-test:
    desc: run unit tests
    aliases: [ut, test]
    deps: [build-dir, mocks]
    dir: backend
    cmds:
      - go test ./... -v -coverprofile .build/cover.out
      - cat .build/cover.out | grep -v "mock_" > .build/cover_clean.out
    sources: 
      - ./**/*.go
    generates:
      - .build/cover.out
      - .build/cover_clean.out
  test-coverage:
    desc: display unit test coverage profile
    aliases: [utc, coverage]
    deps: [unit-test]
    dir: backend
    cmds:
      - covreport -i .build/cover_clean.out -o .build/cover.html
      - open .build/cover.html
  server-docker:
    desc: build docker image for game server
    cmds:
      - docker build -f docker/server.dockerfile -t panda-game-server:latest .
    sources:
      - backend/*
      - docker/server.dockerfile
  run:
    desc: run the panda game locally
    dir: local
    cmd:
      - docker compose up --detach
  stop:
    desc: stop the panda game locally
    dir: local
    cmd:
      - docker compose down