dir: "{{.InterfaceDir}}"
inpackage: true
with-expecter: true
all: true
packages:
  pandagame/internal/mongoconn:
    config:
      recursive: true 
  pandagame/internal/redisconn:
    config:
      recursive: true